version: "3.9"

services:
  financiacio-database:
    image: postgres
    container_name: financiacio-database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=financiacio
      - POSTGRES_DB=financiacio
    volumes:
      - pgdata:/data/postgres
    network_mode: host
      
  app:
    build: .
    container_name: financiacio-back
    ports: 
      - "3333:3333"
    volumes: 
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local